### ISSUE TITLE
[Dry-runner] Implement Zhevana’s ability

### ISSUE THREAD

**Issue by KittySparkles** [KittySparkles/stormbound-kitty#1]
Zhevana’s ability has an effect on mana and should be implemented in the Dry-runner RNG setting, like it is done for Dawnsparks and Frozen Core.

<img width="338" alt="Screenshot 2019-08-04 at 22 03 41" src="https://user-images.githubusercontent.com/53430374/62428616-bcb0d080-b703-11e9-8ca8-9461d3ae5480.png">

**Comment by KittySparkles** [comment]
Done with #34.

**Comment by Neicigam** [comment]
Yay!
