### ISSUE TITLE
[Deck advice] Add a check for inefficient Dragon combos

### ISSUE THREAD

**Issue by KittySparkles** [KittySparkles/stormbound-kitty#131]
- Ludic Matriarchs: https://stormbound-kitty.com/card/N43/display
- Dangerous Suitors: https://stormbound-kitty.com/card/N51/display
- Wandering Wyrms: https://stormbound-kitty.com/card/F9/display
- Sunbeam Serpents: https://stormbound-kitty.com/card/F19/display
- Dreadful Keepers: https://stormbound-kitty.com/card/S4/display

**Comment by jumboduck** [comment]
What are the requirements for this?

**Comment by KittySparkles** [comment]
I guess we should expect dragon cards interacting with another dragon to be in a deck with at least 2 other dragons.
