### ISSUE TITLE
[Deck advice] Add a check for inefficient Lucky Charmers

### ISSUE THREAD

**Issue by KittySparkles** [KittySparkles/stormbound-kitty#132]

**Comment by jumboduck** [comment]
What's a good number of Pirates in deck to make this card worth it?

**Comment by KittySparkles** [comment]
I would say Lucky Charmers + 4 would work; Lucky Charmers + 5+ would be ideal. Below 4 means Lucky Charmers is no longer the main focus of the deck, which is unlikely for a Lucky Charmers deck.
