### ISSUE TITLE
[Deck advice] Add a check for inefficient Northsea Dog

### ISSUE THREAD

**Issue by KittySparkles** [KittySparkles/stormbound-kitty#136]
Northsea Dog in an expensive deck without discard mechanics (First Mutineer) could be considered inefficient since it is unlikely to be played as last card.

**Comment by Stratadox** [comment]
If the deck has mana producing cards like Frozen Core or especially Gift of the Wise, a card like Northsea Dog might still make sense even if the rest of the cards are relatively expensive.
