### ISSUE TITLE
[Fan-kit] Add avatars

### ISSUE THREAD

**Issue by KittySparkles** [KittySparkles/stormbound-kitty#252]

**Comment by mintzzoa** [comment]
Shall I make a new page with `Avatars - Fan-kit` and corresponding data files?

**Comment by KittySparkles** [comment]
If you’d like, you create the underlying ground work (creating the page, adding the URL to the router, displaying the layout, etc.), but ultimately I need to talk to Brzoza to get all avatars in good quality, so I’m not sure how far you can go really. :)

**Comment by mintzzoa** [comment]
Ah, I see, was going to ask how you got the assets and stuff.
I haven't really participated in a proper project before, so I guess I shan't risk committing bad code :shrug:
I'll tinker on other issues little by little when I have time, so that you can ~~kick me out because I troll too much~~ see if I am helpful enough.

**Comment by KittySparkles** [comment]
@mintzzoa That’s very kind of you, and I’m super happy welcoming contributors! Regarding the quality of the code, don’t worry too much: first of all, I would review it before it gets merged and secondly, we have tests and code-listing so it’s pretty safe overall. 

If you would like to contribute, you could consider tackling something like #256. It’s pretty isolated of a feature, relatively straightforward to write, and fully covered with tests. @jumboduck actually wrote quite a few of these advice while he was learning JavaScript, so he could also give a hint or two.

If you‘re interested, feel free to start the conversation in #256, or to DM me on Discord and we can take it from there. Otherwise, no worries, I’ll get to it eventually. 😊

**Comment by mintzzoa** [comment]
Thank you for your kind response.
Okay I'll start working on #256, and DM you for some trivial things

**Comment by KittySparkles** [comment]
Done with https://github.com/KittySparkles/stormbound-kitty/commit/eb1e229401d3f4bc3bb164d5c85e99ad3a4012e1.
