### ISSUE TITLE
[Battle Sim] Implement proper deck mechanisms

### ISSUE THREAD

**Issue by KittySparkles** [KittySparkles/stormbound-kitty#3]
The current drawing/cycling mechanisms from the battle simulator are pretty rough and do not reflect actual mechanisms from the game replicated in the dry-runner and tracker. It would be good to bring them in somehow.

**Comment by cygwins** [comment]
Great job there, thank you for all your effort!
How do you know the draw rate? Also, the card just got cycled back CAN be redrawn next turn without cycling again, from my experiences. It happened several times, and the card can be any card, doesn't have to be the three-cost discard a card pirate.

**Comment by KittySparkles** [comment]
Hello, and thank you for the kind words. 😊 

Regarding the drawing mechanics, I outline them in that guide: https://stormbound-kitty.com/guides/drawing. This is the result of extensive research from various members of the community, as well as hints and explanations from Arano and Kuldotha, both former members of the Paladin Studios team behind Stormbound.

I’m also going to close that story because a) nobody uses the battle sim, so who cares and b) this was enough of a pain to make it work in the deck dry-runner that I don’t want to live through that again. :D
